# Generated by Django 4.2 on 2023-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='Approval_status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Blog_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Date_blog',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Attendance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Certificate',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Enrollment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Is_paid_subscription',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Pending_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='Teacher_response',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Correct_answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Lock',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option1',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option2',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Option3',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Time_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='Time_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Acquired_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Grade',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Student_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Time_stop',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_results',
            name='Total_marks',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Feedback_text',
            field=models.TextField(default='Nil', null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Rating_score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Submission_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Teacher_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='Teacher_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Begin_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Completion_timestamp',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Course_chapter_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Course_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Student_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Student_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='learning_progress',
            name='Subject_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='From_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Message_content',
            field=models.TextField(default='Nil', null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='To_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='About_website',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Average_review_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='First_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Introduction_brief',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_courses_completed',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_courses_enrolled',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_enrolled_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Num_of_reviews',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Qualification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='User_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='New_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='Old_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='User_category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_Is_mandatory',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_Is_open_for_free',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_Time_required_in_sec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_Content_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_text_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Chapter_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Course_brief',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Course_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Course_fee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Course_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Language',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Num_of_assignments',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Num_of_chapters',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Subject_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
