# Generated by Django 4.2 on 2023-05-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_alter_blogs_approval_status_alter_blogs_blog_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Registration_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
